In [2]:
import numpy as np

# Pair programming NumPy

**Creación y Indexación**:

1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [21]:
array_1= np.random.randint(10,100, 50)
array_1



array([87, 91, 96, 62, 40, 41, 36, 64, 61, 46, 47, 74, 31, 94, 75, 51, 58,
       53, 54, 78, 33, 14, 60, 91, 88, 46, 10, 54, 12, 65, 71, 55, 26, 86,
       74, 33, 19, 78, 90, 73, 34, 16, 84, 45, 62, 73, 76, 66, 54, 17])

In [24]:
array_multiplo_5= array_1[array_1 %5 ==0]
array_multiplo_5

array([40, 75, 60, 10, 65, 55, 90, 45])

2- Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [26]:
array_2 = np.random.randint(1,21,30)
array_2

array([20,  5, 15,  1, 20,  7,  2,  1,  8,  3,  7, 13, 13,  4, 14, 19, 11,
       12,  4, 16,  7,  5, 11, 12, 11, 19,  2, 20, 14, 19])

In [28]:
array_2[1::2]

array([20,  5, 15,  1, 20,  7,  2,  1,  8,  3,  7, 13, 13,  4, 14, 19, 11,
       12,  4, 16,  7,  5, 11, 12, 11, 19,  2, 20, 14, 19])

3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [69]:
array_4_bi = np.random.rand(4,6)
array_5 = array_4_bi +4


In [71]:
array_5_round = np.round(array_5,2)
array_5_round

array([[4.91, 4.39, 4.02, 4.92, 4.81, 4.  ],
       [4.14, 4.87, 4.01, 4.46, 4.39, 4.21],
       [4.19, 4.21, 4.62, 4.96, 4.03, 4.59],
       [4.62, 4.08, 4.52, 4.09, 4.68, 4.72]])

In [74]:
#accedemos a la última fila

array_5_round[-1, :]

array([4.62, 4.08, 4.52, 4.09, 4.68, 4.72])

4- Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [81]:
array_6 = np.round(np.random.rand(6,4), 2)
array_6 

array([[0.04, 0.03, 0.99, 0.75],
       [0.93, 0.98, 0.22, 0.21],
       [0.05, 0.86, 0.58, 0.4 ],
       [0.99, 0.84, 0.75, 0.79],
       [0.15, 0.3 , 0.7 , 0.92],
       [0.86, 0.68, 0.81, 0.55]])

5b - Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [84]:
array_7 = np.random.randint(-50, 50, 30)
array_7

array([-15, -12,  48, -22, -14, -27,  26,  10, -23, -21, -11, -20,  10,
        40,  43, -14,  -5,  -7, -15, -21,  46, -44,   2,  29, -32,   1,
       -13,  19, -18, -32])

In [89]:
array_7_negativo = array_7[array_7<0]
array_7_negativo

array([-15, -12, -22, -14, -27, -23, -21, -11, -20, -14,  -5,  -7, -15,
       -21, -44, -32, -13, -18, -32])

6 - Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [95]:
array_8 = np.round(np.random.rand(10),2)
array_8

array([0.36, 0.98, 0.65, 0.42, 0.94, 0.06, 0.66, 0.73, 0.1 , 0.94])

In [99]:
#elementos mayores a 0.5

array_8[array_8>0.5]

array([0.98, 0.65, 0.94, 0.66, 0.73, 0.94])

In [98]:
#posición elementos
posicion_array_8 = np.where(array_8 > 0.5)
posicion_array_8

(array([1, 2, 4, 6, 7, 9]),)

7- Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [101]:
array_9 = np.random.randint(1,101,40)
array_9

array([28, 16, 44, 92, 43,  4, 95, 50, 88, 40, 87, 95, 95, 33,  5, 45, 70,
       33, 78, 55,  4, 26, 23,  8, 97, 68, 43, 94, 36, 35, 80, 16, 65, 30,
       52, 93,  2, 46, 85, 62])

In [106]:
array_9_3= array_9[array_9 % 3 == 0] & array_9[array_9 % 4 == 0]
array_9_3

SyntaxError: invalid syntax (3094395488.py, line 1)

In [ ]:
array_9_4 = 

8- BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

**Reshape y Transpose**:

**Ejercicios con reshape**:

1- Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio

2- Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

3- Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

**Ejercicios con transpose**:

4- Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

5- Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

Preguntas teóricas:

6- ¿Qué diferencia existe entre el reshape y el transpose?

7 - ¿Y entre el transpose y el swapaxes?

**Funciones Aritméticas y Estadísticas**:

1 - Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:

Si el valor del array es igual que la media, se reemplaza por "A".
Si el valor del array es mayor que la media, se reemplaza por "B".
Si el valor del array es menor que la media, se reemplaza por "C".
Si el valor es igual que el máximo, se reemplaza por "D".
Si el valor es igual que el mínimo, se reemplaza por "E".

- a modo de ejemplo. Si tenemos el siguiente array
[[[0.4, 0.7, 0.2, 0.9, 0.2],
    [0.1, 0.9, 0.6, 0.1, 0.2],
    [1. , 0.2, 0.1, 0.8, 0.3]],

[[0. , 0.3, 0.4, 0.5, 0.1],
    [0.5, 0.7, 0.9, 0. , 0.8],
    [0.5, 0.3, 0.5, 0.8, 0.1]]])

- sabiendo que la media es 0.4 y el máximo es 1.0 y el mínimo es 0.0

- nuestro array vacío debería quedar como este: 
[[["A", "B", "C", "B", "C"],
    ["C", "B", "B", "C", "C"],
    ["D" , "C", "C", "B", "C"]],

[["E" , "C", "A", "B", "C"],
    ["B", "B","B", "E" , "B"],
    ["B", "C", "B", "B", "C"]]])