In [1]:
import numpy as np

# Pair programming NumPy

**Creación y Indexación**:

1- Crea un array 1D con 50 valores aleatorio del 10 al 99. Accede a los elementos en las posiciones múltiplos de 5.

In [2]:
array_1= np.random.randint(10,100, 50)
array_1



array([30, 63, 96, 26, 22, 92, 48, 98, 49, 50, 69, 97, 46, 76, 20, 60, 17,
       17, 37, 74, 25, 52, 34, 17, 91, 20, 86, 80, 20, 95, 78, 45, 50, 95,
       20, 83, 43, 37, 78, 16, 34, 77, 52, 78, 78, 35, 29, 47, 83, 21])

In [3]:
array_multiplo_5= array_1[array_1 %5 ==0]
array_multiplo_5

array([30, 50, 20, 60, 25, 20, 80, 20, 95, 45, 50, 95, 20, 35])

2- Crea un array 1D con 30 valores del 1 al 20 (ambos incluidos). Utiliza indexación para obtener los elementos en las posiciones impares.

In [4]:
array_2 = np.random.randint(1,21,30)
array_2

array([ 9,  6, 11,  8, 19,  3,  8, 13,  1,  9,  9,  8, 13, 12,  7, 15, 17,
       10, 14,  7,  1,  2, 11,  6, 14,  7, 11, 18,  2,  1])

In [5]:
array_2[1::2]

array([ 6,  8,  3, 13,  9,  8, 12, 15, 10,  7,  2,  6,  7, 18,  1])

3- Crea un array 2D de forma (4, 6) con números aleatorios decimales (no deben estar comprendidos solo entre 0 y 1). Accede a la última fila de la matriz. Los decimales deben estar redondeados a 2 decimales.

In [6]:
array_4_bi = np.random.rand(4,6)
array_5 = array_4_bi +4


In [7]:
array_5_round = np.round(array_5,2)
array_5_round

array([[4.43, 4.05, 4.27, 4.19, 4.67, 4.74],
       [4.07, 4.92, 4.21, 4.28, 4.22, 4.38],
       [4.94, 4.4 , 4.13, 4.26, 4.4 , 4.57],
       [4.11, 4.29, 4.37, 4.85, 4.55, 4.52]])

In [8]:
#accedemos a la última fila

array_5_round[-1, :]

array([4.11, 4.29, 4.37, 4.85, 4.55, 4.52])

4- Crea un array NumPy 2D de forma (6, 4) con valores decimales entre 0 y 1. Accede a la segunda columna de la matriz. Los números deben estar redondeados a 2 decimales.

In [9]:
array_6 = np.round(np.random.rand(6,4), 2)
array_6 

array([[0.94, 0.69, 0.24, 0.78],
       [0.36, 0.66, 0.91, 0.14],
       [0.35, 0.48, 0.75, 0.1 ],
       [0.07, 0.44, 0.36, 0.26],
       [0.09, 0.04, 0.05, 0.92],
       [0.74, 0.84, 0.74, 0.17]])

5b - Crea un array 1D con 30 valores enteros aleatorios entre -50 y 50. Extrae los valores negativos.

In [10]:
array_7 = np.random.randint(-50, 50, 30)
array_7

array([ 23,  48, -37, -38,  45,  26,  31,  -2, -23,   1,  44,  -7,   4,
        28, -23, -39, -10,   1, -30, -35,  20,  26,  39, -43,  16,   6,
       -41,  12, -30,  -5])

In [11]:
array_7_negativo = array_7[array_7<0]
array_7_negativo

array([-37, -38,  -2, -23,  -7, -23, -39, -10, -30, -35, -43, -41, -30,
        -5])

6 - Crea un array 1D con 10 valores entre 0 y 1. Redondea los decimales a 2. Obtén los elementos cuyo valor es mayor que 0.5. ¿En que posición/es están esos elementos?

In [12]:
array_8 = np.round(np.random.rand(10),2)
array_8

array([0.89, 1.  , 0.63, 0.74, 0.24, 0.3 , 0.26, 0.21, 0.41, 0.09])

In [13]:
#elementos mayores a 0.5

array_8[array_8>0.5]

array([0.89, 1.  , 0.63, 0.74])

In [14]:
#posición elementos
posicion_array_8 = np.where(array_8 > 0.5)
posicion_array_8

(array([0, 1, 2, 3]),)

7- Crea un array 1D con 40 valores del 1 al 100 (ambos incluidos). Obtén los elementos que son divisibles por 3 y por 4.

In [15]:
array_9 = np.random.randint(1,101,40)
array_9

array([ 72,  61,  68,  20,  52, 100,  91,  51,  92,  91,  40,  43,  43,
        35,   3,  41,  18,  50,  20,  72,  76,  27,  19,   1,  61,  56,
        74,  49,  77,  68,  93,  48,  16,  46,  25,  63,  73,  31,  49,
        43])

In [17]:
array_9_3= array_9[array_9 % 3 == 0] & array_9[array_9 % 4 == 0]
array_9_3

ValueError: operands could not be broadcast together with shapes (9,) (14,) 

In [ ]:
array_9_4 = 

8- BONUS: Crea un array 3D de forma (2, 3, 5) y 50 elementos con números enteros entre 0 y 100 (ambos incluidos). Reemplaza los elementos en posiciones múltiplos de 3 por 0.

In [20]:
array_3D = np.random.randint(0, 101, (2,3,5))
array_3D


array([[[60, 48, 45, 19, 19],
        [77,  1,  2, 20, 69],
        [28, 79, 89, 62, 35]],

       [[38, 38, 45, 58, 87],
        [35, 76, 10, 69, 49],
        [54, 74, 93, 50, 58]]])

In [55]:
#Reemplaza los elementos en posiciones múltiplos de 3 por 0.


60

In [63]:
cada3 = array_3D[:,:,::3]
cada3

# Así accede al elemento 3 de cada fila

array([[[60, 19],
        [77, 20],
        [28, 62]],

       [[38, 58],
        [35, 69],
        [54, 50]]])

In [69]:
array_3D[:,:,::3]=0
array_3D

array([[[ 0, 48, 45,  0, 19],
        [ 0,  1,  2,  0, 69],
        [ 0, 79, 89,  0, 35]],

       [[ 0, 38, 45,  0, 87],
        [ 0, 76, 10,  0, 49],
        [ 0, 74, 93,  0, 58]]])

In [21]:
#nota: para que haya 50 elementos se debe modificar la forma del array, 
# ya que con la forma (2,3,5) dan 30 elementos
array_3D.size 

30

**Reshape y Transpose**:

**Ejercicios con reshape**:

1- Crea un array 3D de forma (2, 3, 4) con valores aleatorios entre 1 y 100 (ambos inclusive). Utiliza reshape para convertirlo en un array 2D. Deberás pensar en la forma que es correcta para hacer este cambio

2- Crea un array 3D de forma (3, 4, 5) con valores enteros del 1 al 60 (sin incluir). Utiliza reshape para convertirlo en un array 2D.

In [71]:
otro_3D =  np.random.randint(0, 60, (3,4,5))
otro_3D

array([[[37, 28, 24, 59,  0],
        [ 2, 10, 19, 53, 25],
        [10, 43, 40, 26, 16],
        [32, 53, 12, 30,  2]],

       [[59, 50, 37, 29,  5],
        [51, 32, 50, 43, 39],
        [56, 33, 58, 36, 52],
        [10,  1, 36, 32,  3]],

       [[23,  6, 20,  4, 46],
        [39,  8, 27, 26, 50],
        [37, 52, 22, 51, 43],
        [38,  0, 35, 53, 16]]])

In [82]:
otro_3D_reshape = np.reshape(otro_3D, (10,6))
otro_3D_reshape

array([[37, 28, 24, 59,  0,  2],
       [10, 19, 53, 25, 10, 43],
       [40, 26, 16, 32, 53, 12],
       [30,  2, 59, 50, 37, 29],
       [ 5, 51, 32, 50, 43, 39],
       [56, 33, 58, 36, 52, 10],
       [ 1, 36, 32,  3, 23,  6],
       [20,  4, 46, 39,  8, 27],
       [26, 50, 37, 52, 22, 51],
       [43, 38,  0, 35, 53, 16]])

In [84]:
#para comprobar el número de dimensiones:
otro_3D_reshape.ndim 

2

3- Crea un array 3D de forma (4, 3, 2) con valores aleatorios entre 0 y 1. Utiliza reshape para convertirlo en un array 2D.

**Ejercicios con transpose**:

4- Utiliza el array 3D del ejercicio 2 de reshape. Utiliza transpose para permutar los ejes y obtener un nuevo array con forma (5, 4, 3).

In [85]:
otro_3D 

array([[[37, 28, 24, 59,  0],
        [ 2, 10, 19, 53, 25],
        [10, 43, 40, 26, 16],
        [32, 53, 12, 30,  2]],

       [[59, 50, 37, 29,  5],
        [51, 32, 50, 43, 39],
        [56, 33, 58, 36, 52],
        [10,  1, 36, 32,  3]],

       [[23,  6, 20,  4, 46],
        [39,  8, 27, 26, 50],
        [37, 52, 22, 51, 43],
        [38,  0, 35, 53, 16]]])

In [87]:
otro_3D_trans = np.transpose(otro_3D)
otro_3D_trans

array([[[37, 59, 23],
        [ 2, 51, 39],
        [10, 56, 37],
        [32, 10, 38]],

       [[28, 50,  6],
        [10, 32,  8],
        [43, 33, 52],
        [53,  1,  0]],

       [[24, 37, 20],
        [19, 50, 27],
        [40, 58, 22],
        [12, 36, 35]],

       [[59, 29,  4],
        [53, 43, 26],
        [26, 36, 51],
        [30, 32, 53]],

       [[ 0,  5, 46],
        [25, 39, 50],
        [16, 52, 43],
        [ 2,  3, 16]]])

5- Utiliza el array 3D del ejercicio 3 de reshape. Utiliza transpose para cambiar el orden de los ejes y obtener un nuevo array con forma (3, 2, 4).

Preguntas teóricas:

6- ¿Qué diferencia existe entre el reshape y el transpose?

- El **transpose** cambia la posición de 3 dimensiones, donde reorganizan el número de matrices, de filas y de columnas.

- En cambio el **reshape** cambia la forma el array, pero no su contenido. El número total de elementos siempre será el mismo.

7 - ¿Y entre el transpose y el swapaxes?

**Funciones Aritméticas y Estadísticas**:

_____

1 - Crea un array de tres 3D con elementos entre el 0 y 1 de forma (2, 3, 5) cuyos valores solo tengan 1 decimal.

In [217]:
array_unos_ceros = np.round(np.random.rand(2,3,5),1)
array_unos_ceros

array([[[0.8, 0.5, 0.8, 0.3, 0.8],
        [0.2, 0. , 0.6, 0.2, 0.3],
        [0.4, 0.4, 0.1, 0.6, 0.3]],

       [[0.5, 0.2, 0. , 0.5, 0.8],
        [0.4, 0.5, 0.6, 0.2, 0.1],
        [0.2, 0.1, 0.1, 0.6, 0.9]]])

2 - Crea un array vacío con la misma forma y dimensiones que el array creado anteriormente. Vamos a reemplazar los valores de la matriz vacía que nos acabamos de crear pero basándonos en los valores del primer array bajo las siguientes condiciones:


- Si el valor del array es igual que la media, se reemplaza por "A".

In [218]:
#Creamos un array vacío de strings:

array_vacio_str = np.empty((2,3,5), str)
array_vacio_str

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']],

       [['', '', '', '', ''],
        ['', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

Si el valor del array es igual que la media, se reemplaza por "A".

In [219]:
#buscamos la media de array_unos_ceros

media = np.round(np.mean(array_unos_ceros),1).astype(str)
media

#ponemos .astype(str) para transformar los datos de float a cadena, y para que posteriormente pueda hacer la comparación

'0.4'

In [220]:
# Reemplazar los valores en el array vacío basándonos en las condiciones dadas
array_vacio_str[array_unos_ceros.astype(str) == media] = "A"
array_vacio_str

#nota: añadimos .astype(str) para que pueda comparar los datos de la media, que hemos pasado a string, con la "A", que también es string

array([[['', '', '', '', ''],
        ['', '', '', '', ''],
        ['A', 'A', '', '', '']],

       [['', '', '', '', ''],
        ['A', '', '', '', ''],
        ['', '', '', '', '']]], dtype='<U1')

- Si el valor del array es mayor que la media, se reemplaza por "B".


In [221]:
array_vacio_str[array_unos_ceros.astype(str) > media] = "B"
array_vacio_str

array([[['B', 'B', 'B', '', 'B'],
        ['', '', 'B', '', ''],
        ['A', 'A', '', 'B', '']],

       [['B', '', '', 'B', 'B'],
        ['A', 'B', 'B', '', ''],
        ['', '', '', 'B', 'B']]], dtype='<U1')

- Si el valor del array es menor que la media, se reemplaza por "C".

In [222]:
array_vacio_str[array_unos_ceros.astype(str) < media] = "C"
array_vacio_str

array([[['B', 'B', 'B', 'C', 'B'],
        ['C', 'C', 'B', 'C', 'C'],
        ['A', 'A', 'C', 'B', 'C']],

       [['B', 'C', 'C', 'B', 'B'],
        ['A', 'B', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'B']]], dtype='<U1')

- Si el valor es igual que el máximo, se reemplaza por "D".

In [223]:
#buscamos el valor máximo de array_unos_ceros

max = np.round(np.max(array_unos_ceros),1).astype(str)
max

#ponemos .astype(str) para transformar los datos de float a cadena, y para que posteriormente pueda hacer la comparación

'0.9'

In [224]:
array_vacio_str[array_unos_ceros.astype(str) == max] = "D"
array_vacio_str

array([[['B', 'B', 'B', 'C', 'B'],
        ['C', 'C', 'B', 'C', 'C'],
        ['A', 'A', 'C', 'B', 'C']],

       [['B', 'C', 'C', 'B', 'B'],
        ['A', 'B', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'D']]], dtype='<U1')

- Si el valor es igual que el mínimo, se reemplaza por "E".

In [225]:
#buscamos el valor mínimo de array_unos_ceros

min= np.round(np.min(array_unos_ceros),1).astype(str)
min

#ponemos .astype(str) para transformar los datos de float a cadena, y para que posteriormente pueda hacer la comparación

'0.0'

In [226]:
array_vacio_str[array_unos_ceros.astype(str) == min] = "E"
array_vacio_str

array([[['B', 'B', 'B', 'C', 'B'],
        ['C', 'E', 'B', 'C', 'C'],
        ['A', 'A', 'C', 'B', 'C']],

       [['B', 'C', 'E', 'B', 'B'],
        ['A', 'B', 'B', 'C', 'C'],
        ['C', 'C', 'C', 'B', 'D']]], dtype='<U1')